### ISSUE TITLE
userDefinedExcludes doesn't seem to work

### ISSUE THREAD

**Issue by jaouenk** [Esri/angular-cli-esri-map#54] opened 2020-02-04 14:00 UTC
Hello

Follow up this issue  https://github.com/Esri/arcgis-webpack-plugin/issues/78#issuecomment-581798687, the userDefinedExcludes doesn't seem to affect the bundle size.

Using branch : arcgis-webpack-angular

Thank you

**Comment by andygup** [comment] 2020-02-04 15:34
@jaouenk This is expected behavior. As mentioned in the other issue, in the ArcGIS API for JavaScript 4.x there is shared code among all layers and what you are seeing is that you have essentially reached the minimum bundle size for the API. Another way to look at it is you are attempting to exclude bundles that have already been excluded by the webpack plugin because you they aren't being imported into your app.

**Comment by jaouenk** [comment] 2020-02-05 10:59
I'm ok for layers but what about Widgets ?

```
new ArcGISPlugin({
      userDefinedExcludes: [
        "arcgis-js-api/widgets/BasemapGallery",
        "arcgis-js-api/widgets/BasemapToggle",
        "arcgis-js-api/widgets/Bookmarks",
        "arcgis-js-api/widgets/BrowseItems",
        "arcgis-js-api/widgets/ClassedColorSlider",
        "arcgis-js-api/widgets/ClassedSizeSlider",
        "arcgis-js-api/widgets/ColorPicker",
        "arcgis-js-api/widgets/ColorRampSelector",
        "arcgis-js-api/widgets/ColorSlider",
        "arcgis-js-api/widgets/Compass",
        "arcgis-js-api/widgets/CoordinateConversion",
        "arcgis-js-api/widgets/Directions",
        "arcgis-js-api/widgets/DirectLineMeasurement3D",
        "arcgis-js-api/widgets/DistanceMeasurement2D",
        "arcgis-js-api/widgets/Editor",
        "arcgis-js-api/widgets/Expand",
        "arcgis-js-api/widgets/Feature",
        "arcgis-js-api/widgets/FeatureForm",
        "arcgis-js-api/widgets/FeatureTemplates",
        "arcgis-js-api/widgets/Fullscreen",
        "arcgis-js-api/widgets/HeatmapSlider",
        "arcgis-js-api/widgets/Histogram",
        "arcgis-js-api/widgets/HistogramRangeSlider",
        "arcgis-js-api/widgets/Home",
        "arcgis-js-api/widgets/LayerList",
        "arcgis-js-api/widgets/Legend",
        "arcgis-js-api/widgets/Locate",
        "arcgis-js-api/widgets/NavigationToggle",
        "arcgis-js-api/widgets/OpacitySlider",
        "arcgis-js-api/widgets/Popup",
        "arcgis-js-api/widgets/Print",
        "arcgis-js-api/widgets/RasterSymbologyEditor",
        "arcgis-js-api/widgets/RendererSlider",
        "arcgis-js-api/widgets/ScaleBar",
        "arcgis-js-api/widgets/ScaleRangeSlider",
        "arcgis-js-api/widgets/Search",
        "arcgis-js-api/widgets/SizeSlider",
        "arcgis-js-api/widgets/Sketch",
        "arcgis-js-api/widgets/Slice",
        "arcgis-js-api/widgets/Slider",
        "arcgis-js-api/widgets/Spinner",
        "arcgis-js-api/widgets/SymbolStyler",
        "arcgis-js-api/widgets/Tags",
        "arcgis-js-api/widgets/TimeSlider",
        "arcgis-js-api/widgets/Track",
        "arcgis-js-api/widgets/UnivariateColorSizeSlider",
        "arcgis-js-api/widgets/Zoom",
      ],
    })
```
The bundle size doesn't change either.

**Comment by andygup** [comment] 2020-02-05 15:44
That's correct. You are at minimum bundle size for the entire API. 

Note, with each new release we are getting closer to ESM compliance and significantly improving dependency management. ESM compliance is our ultimate goal. I'm going to go ahead and close this issue, thanks for reaching out.

**Closed by andygup** 2020-02-05 15:44 UTC
