### ISSUE TITLE
`Unhandled Promise rejection` errors are thrown on SceneView panning and zooming

### ISSUE THREAD

**Issue by bpo19** [Esri/angular-cli-esri-map#108] opened 2021-06-17 16:58 UTC
`Unhandled Promise rejection` errors are thrown in a simple Angular 12 application using esri-loader 3.1.0 and ArcGIS JS API 4.19 in at least these situations:
1. On creating a SceneView with a WebMap or Map
2. On panning and zooming the SceneView

The console is flooded with errors and any other relevant information can be easily missed.
The errors started to appear in ArcGIS JS API 4.18 and are present in the next version (4.20) as well.

A simple application that demonstrates the issue can be found here: https://github.com/bpo19/arcgis-js-sample.

In order to reproduce the bug we followed the Esri sample from https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli
where we replaced the @arcgis/core library with esri-loader.

Console errors thrown by SceneView are: `Console errors `Unhandled Promise rejection: Aborted ; Zone: <root> ; Task: null ; Value: DOMException: Aborted undefined``

**Comment by andygup** [comment] 2021-06-18 22:36
Duplicate of https://github.com/Esri/angular-cli-esri-map/issues/109. I'll go ahead and close this and respond back on the original issue.

**Closed by andygup** 2021-06-18 22:36 UTC
