### ISSUE TITLE
click event hitTest() result undefined 

### ISSUE THREAD

**Issue by tatemcg** [Esri/angular-cli-esri-map#78] opened 2020-09-17 07:15 UTC
Hello,
I seem to be having trouble getting the result back when using the hitTest() on a click event.  
The hitTest() in  ngOnInit() works fine and return the expected result for the initial displaying layer (see screenshot).  But when I switch to a different layer, the second hitTest() in ngOnChanges() does not return anything(undefined) in the console (see screenshot).
Not sure what I did wrong, any pointers/help to resolve this issue would be appreciated.  Thanks!  

github link:  https://github.com/tatemcg/ng_10_esri
stackblitz link: https://stackblitz.com/github/tatemcg/ng_10_esri

1st layer - Point
![image](https://user-images.githubusercontent.com/52325547/93432355-09655580-f88b-11ea-8fb1-90e56b819969.png)

2nd layer - County
![image](https://user-images.githubusercontent.com/52325547/93432518-46314c80-f88b-11ea-9f25-d79bc1b6fcc9.png)

**Comment by andygup** [comment] 2020-09-17 14:54
Hi @tatemcg, you can't intermix Angular lifecycle events such as `ngOnChanges()` with events or change handling created by the ArcGIS API for JavaScript. I moved all the `ngOnChanges()` code to the bottom of the `ngOnInit()` code block and most everything worked. After making that change, there's just an undefined `graphic` error in your code when you click on the map.

**Comment by tatemcg** [comment] 2020-09-17 16:53
Andy,
is this what you mean by moving all the code in ngOnChanges() to the bottom of the ngOnInit()(see screenshot)? if so its not working. 
![image](https://user-images.githubusercontent.com/52325547/93502419-50c80200-f8dc-11ea-956e-80e6da64ea55.png)

**Comment by andygup** [comment] 2020-09-17 19:27
Sorry, here's some additional information that might help clarify my earlier comment. Looking at the code, the issue might be caused by initializing multiple instances of the `click` event listener on `this._view`.  Maybe take a different approach that uses dedicated click listeners for each layer, instead of recreating the listeners when the user selects a different radio button. Does that help?

**Comment by andygup** [comment] 2020-09-17 19:28
Or, perhaps use a single click listener and then filter the results by layer type within the event response callback.

**Comment by tatemcg** [comment] 2020-09-17 23:14
hi, I tried using implement what you previous mentioned, but the hitTest() still doesn't work after switching to a county layer. Not sure where it went wrong this time. 
![image](https://user-images.githubusercontent.com/52325547/93537558-76233300-f911-11ea-984c-eec921eb9e9b.png)

**Comment by andygup** [comment] 2020-09-18 17:43
Take a look at the concepts and patterns in this codepen: https://codepen.io/andygup/pen/yLORJLy?editors=1000. Note, you can control the `hitTest()` using layer visibility and just a reminder that it does not return detailed attribute and spatial information about the actual feature represented in the layer.

**Comment by tatemcg** [comment] 2020-09-24 05:34
I was able to get to work by reverting to an older version of the esri-loader and arcgis-js-api types.


![image](https://user-images.githubusercontent.com/52325547/94104731-4ab2b380-fdfd-11ea-98bf-8fe2bea224b4.png)


I'm not sure whats the reason why its working in ArcGIS JS API v4.13 and not in v4.16.  Any thoughts?

**Comment by andygup** [comment] 2020-09-24 14:46
It works in my [codepen](https://codepen.io/andygup/pen/yLORJLy?editors=1000) so I'm guessing it's possibly something in your code. Since this is related specifically to the JS API we have to troubleshoot it outside of Angular to try and narrow down the issue. Can you create a codepen that reproduces your issue?

**Comment by andygup** [comment] 2020-10-01 17:20
Closing... feel free to post new comments if something else comes up.

**Closed by andygup** 2020-10-01 17:20 UTC
