### ISSUE TITLE
Point Clustering

### ISSUE THREAD

**Issue by dealsmyself** [Esri/angular-cli-esri-map#23] opened 2019-02-08 04:07 UTC
please help me with a sample to perform a point clustering using esri-loader and angular4,
a sample plunkr  would be awesome as i read all theposts for couple of days and still having issues.

**Comment by andygup** [comment] 2019-02-08 15:50
You'll need to send a link to your starter plunkr project and specific questions so we can troubleshoot it. I recommend stackblitz over plunkr.

**Comment by dealsmyself** [comment] 2019-02-08 16:47
i will try to create a stack-blitz, in the mean time , please point me to a document where i can use esri-loader and cluster because i think i am doing something fundamentally wrong when loading dojo and cluster-layer.js(extras). so that i wont waste your time with basic mistakes on my part.

**Comment by andygup** [comment] 2019-02-08 17:10
>> please point me to a document where i can use esri-loader

Here you go for the esri-loader doc: https://github.com/Esri/esri-loader#table-of-contents. You can also find the basic steps outlined in this repositories README file. 

>> cluster-layer.js(extras)

Are you referring to this repo? https://github.com/Esri/cluster-layer-js. Please note, that's an  old repository using an old version of the ArcGIS API for JavaScript. You'll need to update the code to using the latest version of Bootstrap and the ArcGIS API for JavaScript. 

It would be much easier to create an initial prototype with the ArcGIS API for JavaScript's out-of-the-box clustering functionality. Here's a sample app: https://developers.arcgis.com/javascript/3/jssamples/fl_clustering_basic.html

**Comment by dealsmyself** [comment] 2019-02-09 03:35
sorry for the delay but i am still having the issue
here is the stackblitz
https://stackblitz.com/edit/esri-clus

**Comment by andygup** [comment] 2019-02-09 18:34
Unfortunately, there seems to be a known issue in Stackblitz with loading external files and clusterLayer isn't loading. However, when I removed clusterLayer.js from the map service the app works just fine and the map displayed. To me that says the problem is with clusterLayer.js and not the code in this repository.  

```
Refused to execute script from 'https://esri-clus.stackblitz.io/fcl/clusterLayer.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

I have two suggestions:

1) First, create a working non-Angular, plain old HTML/JavaScript app that uses the cluster layer.

2) Once you have it working outside of Angular, check if clusterLayer.js is available on npm, if not you can upload your own copy, and then try adding it as a dependency to your Stackblitz project.

**Comment by dealsmyself** [comment] 2019-02-12 22:09
Hi , i was not able to create a point cluster, however i was able to achieve it with  esri leaflet, 
i would like to know is it acceptable as my requirement is i have to do with  arcgis only.
thank you

**Comment by andygup** [comment] 2019-02-25 20:20
It's sounds like you got your project working, so I'm going to close this issue. We are aiming to have clustering in the ArcGIS API for JavaScript 4.x some time this year.

**Closed by andygup** 2019-02-25 20:20 UTC

**Comment by itsme-cr** [comment] 2021-08-20 06:15
hey @andygup, do we have option to use clustering using esri-loader? or can u pls suggest me some other way to use clustering in angular using esri map. Thanks!!

**Comment by andygup** [comment] 2021-08-20 13:59
@itsme-cr here is a clustering sample: https://developers.arcgis.com/javascript/latest/sample-code/featurereduction-cluster/ Angular shouldn't affect the functionality.
