### ISSUE TITLE
esri loader for 4.8 / CoordinateConversion error

### ISSUE THREAD

**Issue by jcarasick** [Esri/angular-cli-esri-map#15] opened 2018-07-19 21:47 UTC
I'm seeing this in my console after upgrading to the new version of the esri loader. Any ideas?

[esri.widgets.CoordinateConversion.CoordinateConversionViewModel]
dojo.js:249
h {name: "coordinate-conversion:local-storage-read-error", message: "Could not get widget state from stored JSON.", details: Object}
dojo.js:249
details:Object {error: TypeError: Cannot read property 'formats' of undef…}
message:"Could not get widget state from stored JSON."
name:"coordinate-conversion:local-storage-read-error"
__proto__:a {constructor: , toJSON: , type: "error"}
constructor:function h(c,e,b){ … }
[[FunctionLocation]]:internal#location
[[Scopes]]:Scopes[3]
arguments:null
caller:null
fromJSON:function(a){ … }
length:3
name:"h"
prototype:a {constructor: , toJSON: , type: "error"}
__proto__:function a(e,l,h){ … }
toJSON:function(){ … }
[[FunctionLocation]]:internal#location
[[Scopes]]:Scopes[3]
arguments:null
caller:null
length:0
name:""
prototype:Object {constructor: }
constructor:function(){ … }
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}
__proto__:function () { … }
type:"error"

**Comment by andygup** [comment] 2018-07-19 22:56
@jcarasick I'm unable to reproduce using `esri-loader` version `2.4.0` on Chrome or Safari latest version: https://stackblitz.com/edit/angular-cli-esri-map2-teusey?file=src%2Fapp%2Fesri-map%2Fesri-map.component.ts

Can you provide a stackblitz sample that reproduces the issue?

**Comment by jcarasick** [comment] 2018-07-20 14:47
Yeah, this was my fault. forgot to update the css and had a pointer back to 4.7 api in my loader. Error seems to have gone away with those updated. Sorry for the false alarm.

As a side note i see in 4.7 the css had esri-widget-button and now in 4.8 it's esri-widget--button (an extra dash in there). Is there a way to get all the css changes made between versions?

**Comment by andygup** [comment] 2018-07-20 14:54
Gotcha, glad you got it figured out, I'll go ahead and close this issue out. 

>  Is there a way to get all the css changes made between versions?

We are trying to capture all breaking css changes in the JS API release notes. 

For example, the button styling changed at 4.8: https://developers.arcgis.com/javascript/latest/guide/release-notes/index.html#button-styling

**Closed by andygup** 2018-07-20 14:54 UTC

**Comment by jcarasick** [comment] 2018-07-20 15:35
perfect. Good to see it there. I must of glossed over that line due to all the new cool things i was reading about 4.8 :)
